runtime: nodejs18
service: santander-test-frontend
handlers:
  - url: /
    static_files: dist/santander-test-frontend/index.html
    upload: dist/santander-test-frontend/index.html

  - url: /(.*)
    static_files: dist/santander-test-frontend/\1
    upload: dist/santander-test-frontend/(.*)

  - url: /_ah/(.*)
    script: auto
